version: '3.8'

services:
  app:
    build: .
    container_name: recipe-manager-app
    ports:
      - "8080:8080"
    depends_on:
      - vault
      - postgres
    networks:
      - recipe-manager-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=recipedb
      - POSTGRES_USER=recipeuser
      - POSTGRES_PASSWORD=recipepass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - recipe-manager-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - recipe-manager-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - recipe-manager-network

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=00000000-0000-0000-0000-000000000000
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    entrypoint: >
      /bin/sh -c "
      vault server -dev & 
      sleep 10; 
      export VAULT_ADDR='http://127.0.0.1:8200'; 
      vault login 00000000-0000-0000-0000-000000000000; 
      vault kv put secret/recipe-manager/app recipe.endpoints.username=recipeuser recipe.endpoints.password=recipepass; 
      vault kv put secret/recipe-manager/h2 spring.datasource.url="jdbc:h2:mem:recipedb" spring.datasource.username="sa" spring.datasource.password="";
      vault kv put secret/recipe-manager/postgres spring.datasource.url="jdbc:postgresql://postgres:5432/recipedb" spring.datasource.username="recipeuser" spring.datasource.password="recipepass";
      wait
      "
    networks:
      - recipe-manager-network

networks:
  recipe-manager-network:
    driver: bridge

volumes:
  postgres-data:
  prometheus-data:
  grafana-data:
